server:
  port: 8080

spring:
  application:
    name: palettify
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dbtest}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    open-in-view: false

resilience4j:
  ratelimiter:
    instances:
      paletteExtract:
        limitForPeriod: 6
        limitRefreshPeriod: 60s
        timeoutDuration: 0s

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

logging:
  level:
    com.palettify: DEBUG